# -*- coding: utf-8 -*-
"""Harve Exercícios - Introdução ao Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mqr9yzV6EG9oVmoVV_RHiLzwQZE6M9I_

#Lista de Exercícios de Introdução a Python

1 - (Nível: Fácil) Faça uma função que converta metros para centímetros.
"""

m = float(input('metros: '))
cm = m*100
print('A quantidade de {}m corresponde a: {}cm'.format(m,cm))

"""2 - (Nível: Fácil) Faça uma função que peça a temperatura em graus Farenheit, transforme e mostre a temperatura em graus Celsius.

Lembrete: A fórmula de transformação é C = (5 * (F-32) / 9).
"""

f= float(input('Qual a temperatura em graus Fahrenheit: '))
c= (f - 32) * (5 / 9)
print('Temperatura em {}°F corresponde à {:.1f}°C'.format(f,c))

"""3 - (Nível: Fácil) Faça um programa que leia 5 números informados pelo usuário e informe a soma e a média desses números.

"""

n1 = float(input('Digite um número: '))
n2 = float(input('Digite outro número: '))
n3 = float(input('Digite outro número: '))
n4 = float(input('Digite outro número: '))
n5 = float(input('Digite outro número: '))
s = n1 + n2 + n3 + n4 +n5
m = s/5
print('A soma entre {},{},{},{} e {} vale {} e a média é {}'.format(n1, n2, n3, n4, n5,s,m))

"""4 - (Nível: Fácil) Faça um programa que peça 10 números inteiros para o usuário. 

No final deve apresentar a quantidade de números pares e a quantidade de números impares.

"""

print('='*30)
print('PARES E ÍMPARES')
print('='*30)

par = 0
impar = 0

def resultado(num):
    global par
    global impar
    for i in num:
        if i % 2 == 0:
            par += 1
        else:
            impar += 1

num = []
for c in range(10):
    num.append (int(input('Digite um valor inteiro: ')))

resultado(num)
print('O total de números pares é: {}'.format(par))
print('O total de números ímpares é: {}'.format(impar))

"""5 – (Nível: Intermediário) Escreva uma aplicação pensando em uma loja de tintas. O programa deve pedir ao consumidor o tamanho em m2 da área a ser pintada e apresentar na resposta final a quantidade de latas a serem adquiridas e o valor total. 

Considere que uma lata a tinta é vendida em latas de 3.6 litros e tem um curto de R$82,00, além disso cada 1 litro dessa tinta cobre uma área de 3 m2. 

Qual é o valor total e a quantidade de latas necessárias para uma área de 125 m2?
Resposta: 12 latas – R$ 984,00
"""

print('-'*7)
print('LOJA DE TINTAS')
print('-'*7)

area = float(input('Digite o tamanho da área a ser pintada em m²: '))
latas = (area / 3) / 3.6
valor = latas * 82

print('Você vai precisar de {} lata(s) de tinta'.format(round(latas)))
print('O valor total da compra é R$ {:.2f}'.format(valor))

"""6 – (Nível: Intermediário) Crie uma função que gere e retorne uma lista de valores aleatórios. 

Nessa função o usuário pode entrar com o tamanho da lista, além do valor máximo e o valor mínimo que pode ser gerado aleatoriamente.  

Dica: lembre-se de utilizar (from random import randint)
"""

from random import randint, sample

def aleatorio(min, max):
    lista_num = []
    #continuar = 0
    while len(lista_num) < tam:
        n = randint(min,max)
        if n not in lista_num:
            lista_num.append(n)
            lista_num.sort()
    print(lista_num)
        #continuar += 1

min = int(input("Qual o valor mínimo? "))
max = int(input("Qual o maior valor? "))
tam = int(input("Qual o tamanho da lista? "))
aleatorio(min,max)

"""7 – (Nível: Intermediário) Crie uma função que realize o cálculo e apresente pro usuário o valor do salário bruto, o valor do salário líquido, o valor pago no Imposto de Renda (11%), o valor pago para o INSS (5%) e o ganho com horas extra (20% do valor normal). 

Considere que o usuário passe a quantidade de horas trabalhadas e o valor da hora. 

O que foi apresentado para o usuário se ele trabalhou 45 horas e o valor da sua hora é de R$ 38,00?

Lembrete: Salário Líquido = Salário Bruto – Descontos + Horas Extra, além disso INSS e IR não é calculado sobre horas extras.



Resposta:
Salário Bruto:  1520.0; IR:  167.2; INSS:  76.0; Valor com horas extra:  228.0; Salário Líquido:  1504.8;
"""

def main():
  horas = int(input("Quantidade de horas trabalhadas: "))
  valor_hora = int(input("Valor da hora de trabalho: "))
  salario_bruto = (40 * valor_hora)
  valor_imposto_renda = (salario_bruto * 0.11)
  valor_inss = (salario_bruto * 0.05)
  descontos = (valor_imposto_renda + valor_inss)
  valor_hora_extra = ((valor_hora * 0.20) + valor_hora)
  hora_extra = ((horas - 40) * valor_hora_extra)
  salario_liquido = ((salario_bruto - descontos) + hora_extra)
  print("\nSalario Bruto é R${:.2f}, Salário Líquido R${:.2f} e as Horas Extras corresponde a R$ {:.2f}". format(salario_bruto, salario_liquido, hora_extra))
  print("\nValor pago ref. IR: R${:.2f}, valor pago ref. INSS: R${:.2f}.". format(valor_imposto_renda, valor_inss))
  
main()

"""8 – (Nível: Intermediário) Crie um programa que calcule o fatorial de um número passado pelo o usuário. 

Lembrete: 5! = 5.4.3.2.1 = 120
"""

import math
print('--'*10)
print('FATORIAL')
print('--'*10)

num = int(input('Digite o número para calcular o fatorial: '))
f = math.factorial(num)
print('O número fatorial de {} é: {}'.format(num, f))

"""9 – (Nível: Difícil) Crie um programa que irá verificar a nota de um aluno em uma prova com 10 questões, o programa deve perguntar ao aluno a resposta de cada questão e ao final comparar com o gabarito da prova. 

No final o programa deve apresentar cada resposta (Correta e Incorreta) e como cada resposta correta acrescenta +1 ponto na nota, deve apresentar a nota final. 

Gabarito: (1 – A, 2 – B, 3 – C, 4 – C, 5 – A, 6 – B, 7 – A, 8 – A, 9 – C, 10 – B) 

Lembrete: O aluno pode entrar com respostas (A,B,C) e (a,b,c) e seu programa precisa considerar isso previamente
"""

cprint('--' * 7)
print('PROVA FINAL')
print('--' * 7)

q1 = input('QUESTÃO 1 / Qual a alternativa correta? \n A)\n B)\n C)\n').upper()
q2 = input('QUESTÃO 2 / Qual a alternativa correta? \n A)\n B)\n C)\n').upper()
q3 = input('QUESTÃO 3 / Qual a alternativa correta? \n A)\n B)\n C)\n').upper()
q4 = input('QUESTÃO 4 / Qual a alternativa correta? \n A)\n B)\n C)\n').upper()
q5 = input('QUESTÃO 5 / Qual a alternativa correta? \n A)\n B)\n C)\n').upper()
q6 = input('QUESTÃO 6 / Qual a alternativa correta? \n A)\n B)\n C)\n').upper()
q7 = input('QUESTÃO 7 / Qual a alternativa correta? \n A)\n B)\n C)\n').upper()
q8 = input('QUESTÃO 8 / Qual a alternativa correta? \n A)\n B)\n C)\n').upper()
q9 = input('QUESTÃO 9 / Qual a alternativa correta? \n A)\n B)\n C)\n').upper()
q10 = input('QUESTÃO 10 / Qual a alternativa correta? \n A)\n B)\n C)\n').upper()

nota_final = 0

if q1 == 'A':
    nota_final = 1
    print('QUESTÃO 1 -> CORRETA!')
else:
    nota_final = 0
    print('QUESTÃO 1 -> INCORRETA...!')

if q2 == 'B':
    nota_final += 1
    print('QUESTÃO 2 -> CORRETA!')
else:
    nota_final += 0
    print('QUESTÃO 2 -> INCORRETA...!')

if q3 == 'C':
    nota_final += 1
    print('QUESTÃO 3 -> CORRETA!')
else:
    nota_final += 0
    print('QUESTÃO 3 -> INCORRETA...!')

if q4 == 'C':
    nota_final += 1
    print('QUESTÃO 4 -> CORRETA!')
else:
    nota_final += 0
    print('QUESTÃO 4 -> INCORRETA...!')

if q5 == 'A':
    nota_final += 1
    print('QUESTÃO 5 -> CORRETA!')
else:
    nota_final += 0
    print('QUESTÃO 5 -> INCORRETA...!')

if q6 == 'B':
    nota_final += 1
    print('QUESTÃO 6 -> CORRETA!')
else:
    nota_final += 0
    print('QUESTÃO 6 -> INCORRETA.')

if q7 == 'A':
    nota_final += 1
    print('QUESTÃO 7 -> CORRETA!')
else:
    nota_final += 0
    print('QUESTÃO 7 -> INCORRETA.')

if q8 == 'A':
    nota_final += 1
    print('QUESTÃO 8 -> CORRETA!')
else:
    nota_final += 0
    print('QUESTÃO 8 -> INCORRETA.')

if q9 == 'C':
    nota_final += 1
    print('QUESTÃO 9 -> CORRETA!')
else:
    nota_final += 0
    print('QUESTÃO 9 -> INCORRETA.')

if q10 == 'B':
    nota_final += 1
    print('QUESTÃO 10 -> CORRETA!')
else:
    nota_final += 0
    print('QUESTÃO 10 -> INCORRETA.')

print('Sua nota na prova foi: ', nota_final)

"""10 – (Nível: Difícil) Uma lanchonete tem o seguinte cardápio:

|     Especificação      |     Código    |     Valor (R$)    |
|------------------------|---------------|-------------------|
|     Cachorro Quente    |     100       |     3.75          |
|     Bauru Simples      |     101       |     2.00          |
|     Pastel             |     102       |     1.50          |
|     Hamburguer         |     103       |     3.00          |
|     Refrigerante       |     104       |     2.25          |

Crie um programa que leia o código dos itens pedidos e as quantidades desejadas. No final gere um “Recibo” com o nome do produto pedido, a quantidade pedida, o valor a ser pago por item (preço * quantidade) e no final do recibo o valor total geral do pedido (soma de todos os itens). 

Considere que o cliente deve informar quando o pedido deve ser encerrado.

Lembrete: Em uma lista ou em uma coluna de um dicionário podemos utilizar o método index(valor) para encontrar o índice do valor.
"""

print('-_-'*5)
print('RECIBO')
print('-_-'*5)
print('SEJA BEM VINDO A NOSSA LANCHONETE VIRTUAL! \n\n**MENU**\n')
pedido = []
conta = 0
lanche = {}
quant = 0

def pedidos():
    global conta
    global lanche
    global pedido
    global rotativo
    global quant

    cardapio = {'100': 'Cachorro Quente - R$ 3,75', '101': 'Bauru Simples - R$ 2,00', '102': 'Pastel - R$ 1,50', '103': 'Hamburguer - R$ 3,00', '104': 'Refrigerante - R$ 2,25'}
    for cod, produto in cardapio.items():
        print(cod, produto)
    
    pedido = input('\nDIGITE O CÓDIGO DO ITEM DESEJADO: \n')
    
    if pedido == '100':
        quant = int(input('QUANTAS UNIDADES? \n'))
        dog = 3.75 * quant
        lanche['Cachorro Quente - R$'] = dog
        conta += dog
    elif pedido == '101':
        quant = int(input('QUANTAS UNIDADES? \n'))
        bauru = 2.00 * quant
        lanche['Bauru Simples - R$'] = bauru
        conta += bauru
    elif pedido == '102':
        quant = int(input('QUANTAS UNIDADES? \n'))
        pastel = 1.50 * quant
        lanche['Pastel - R$'] = pastel
        conta += pastel    
    elif pedido == '103':
        quant = int(input('QUANTAS UNIDADES? \n'))
        burger = 3.00 * quant
        lanche['Hamburguer - R$'] = burger
        conta += burger   
    elif pedido == '104':
        quant = int(input('QUANTAS UNIDADES? \n'))
        refri = 2.25 * quant
        lanche['Refrigerante - R$'] = refri
        conta += refri

    
    rotativo = input('\nDESEJA MAIS ALGUM ITEM? DIGITE S PARA SIM OU N PARA NÃO: ').upper()

pedidos()

while rotativo == 'S':
    pedidos()

print('\nITENS: ')
for i, p in lanche.items():
    p_formatado = '{:.2f}'.format(p)
    print(quant, i, p_formatado)

print('\nTOTAL DA COMPRA: R$ {:.2f}'.format(conta))
print('\nSEU PEDIDO SERÁ ENTREGUE EM BREVE!\n')